language: android

script: "./gradlew build"
android:
    components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-15
    - sys-img-armeabi-v7a-android-21
notifications:
    email:
        recipients:
            alberto.minetti@rumbo.com
            stefano.introini@rumbo.com
            felice.giovinazzo@rumbo.com